from __future__ import annotations

from typing import Protocol


class ProjectSummaryStrategy(Protocol):
    def blocker_missing_asset_label(self) -> str: ...

    def missing_asset_message(self, count: int) -> str: ...

    def missing_asset_suggestion(self) -> str: ...

    def missing_asset_fix_action(self) -> str: ...

    def mode_strength_labels(self) -> tuple[str, str]: ...

    def media_settings_fix_action(self, last_message: str) -> str | None: ...

    def duplicate_asset_feedback(self) -> tuple[str, str, str]: ...

    def continuity_feedback(self, *, anchor_coverage: float, jump_rate: float) -> tuple[str, str] | None: ...

    def reasonability_feedback(self) -> tuple[str, str]: ...

    def default_summary_suggestion(self) -> str: ...
